### ISSUE TITLE
Сyclonian

### ISSUE THREAD

**Issue by Edwin18** [project-classic/ClassicCodex#27]
https://classic.wowhead.com/quest=1712

Spammed the whole map.

![image](https://user-images.githubusercontent.com/8036656/64255396-f7d43880-cf29-11e9-9da0-242df3db691b.png)
![image](https://user-images.githubusercontent.com/8036656/64255443-0c183580-cf2a-11e9-8b2c-7d5c47023cf8.png)
![image](https://user-images.githubusercontent.com/8036656/64255458-14707080-cf2a-11e9-8e64-81760a47c60c.png)
![image](https://user-images.githubusercontent.com/8036656/64255471-205c3280-cf2a-11e9-9479-655c99a03015.png)
![image](https://user-images.githubusercontent.com/8036656/64255491-2a7e3100-cf2a-11e9-8bdc-450c3dbace45.png)
![image](https://user-images.githubusercontent.com/8036656/64255515-34079900-cf2a-11e9-8301-9d86565052bf.png)
![image](https://user-images.githubusercontent.com/8036656/64255573-4eda0d80-cf2a-11e9-9124-89d9d58b8cd8.png)
![image](https://user-images.githubusercontent.com/8036656/64255582-56011b80-cf2a-11e9-8e5e-f6bc7f7138c8.png)

And all other locations.
Because of this, I have friezes for a few seconds when moving to other locations.

**Comment by alecjpav** [comment]
It's because it's showing every mob that has a chance of dropping Liferoot for the Cyclonian quest, which is a lot, and drawing far too many icons on the map. Hiding the icons either through the hide button in the quest log or shift+left clicking the icons on the map, or abandoning or completing the quest, will fix it.

**Comment by pgarneau** [comment]
Should be fixed in upcoming release
