### ISSUE TITLE
Nameplate Lua Error

### ISSUE THREAD

**Issue by PaulVlahosCS** [project-classic/ClassicCodex#32]
6x ClassicCodex\quest.lua:406: Attempt to access forbidden object from code tainted by an AddOn
[C]: in function `GetName'
ClassicCodex\quest.lua:406: in function `CheckNamePlate'
ClassicCodex\quest.lua:122: in function <ClassicCodex\quest.lua:24>

Locals:
(*temporary) = <unnamed> {
 0 = <userdata>
}

Occurs whenever rendering a nameplate. Probably has something to do with the fact that I used the workaround of changing the nameplateMaxDistance CVar to 1e4 so I render nameplated from 40 yards away.

**Comment by SwimmingTiger** [comment]
Are you in an instance? Blizzard prohibits the addon from accessing the nameplate in an instance.

```
function CodexQuest:CheckNamePlate()
    -- this line may fix it
    if IsInInstance() then return end
    local something = WorldFrame:GetNumChildren()
    local index = 1
    local plateList = {}
...
```

**Comment by PaulVlahosCS** [comment]
It triggered a lot in instances, but i reset my bugsack and it still threw the errors in the open world in the Blasted Lands.

**Comment by SwimmingTiger** [comment]
I made a mistake, Blizzard just forbids addons to change the friendly nameplates in an instance.

So this could be an imperfect commit (it disables some of the features that might otherwise work) but it may fix the error: https://github.com/SwimmingTiger/ClassicCodex/commit/eca594049dfca14883364b60a934031942cbb607

You can download the fixed package via the following link (you must rename the directory to `ClassicCodex`, otherwise the addon will not load):
https://github.com/SwimmingTiger/ClassicCodex/archive/fix-nameplate-error.zip

**Comment by pgarneau** [comment]
Added to release
